const fs = require('fs');
const path = require('path');

const packagePath = path.join(__dirname, '..', 'package.json');
const packageJson = JSON.parse(fs.readFileSync(packagePath, 'utf8'));

let versionParts = packageJson.version.split('.');
const majorMinor = versionParts.slice(0, 2).join('.'); // "1.1"

// Use the 3rd part for build number because Microsoft Store requires 4th part to be 0
let currentBuild = parseInt(packageJson.build.buildNumber || "0");
let nextBuild = currentBuild + 1;


const baseVersion = `${majorMinor}.${nextBuild}`; // "1.1.1107"
const fullVersion = `${baseVersion}.0`; // "1.1.1107.0"

packageJson.version = baseVersion;
packageJson.build.buildVersion = fullVersion;
packageJson.build.buildNumber = nextBuild.toString();
packageJson.buildTarget = process.env.BUILD_TARGET || 'GITHUB';

// Manually update artifactName to avoid env variable issues
if (packageJson.build && packageJson.build.win) {
    packageJson.build.win.artifactName = `${packageJson.build.productName}_${fullVersion}.\${ext}`;
}




fs.writeFileSync(packagePath, JSON.stringify(packageJson, null, 2));
console.log(`Version: ${baseVersion}, BuildVersion: ${fullVersion}, Updated artifactName.`);

// 2. 自動同步更新 tauri.conf.json 版本號
const tauriConfPath = path.join(__dirname, '..', 'src-tauri', 'tauri.conf.json');
if (fs.existsSync(tauriConfPath)) {
    try {
        const tauriConf = JSON.parse(fs.readFileSync(tauriConfPath, 'utf8'));
        tauriConf.version = baseVersion;
        fs.writeFileSync(tauriConfPath, JSON.stringify(tauriConf, null, 2), 'utf8');
        console.log(`[Sync] tauri.conf.json 版本號已同步更新為: ${baseVersion}`);
    } catch (err) {
        console.error(`[Sync] 更新 tauri.conf.json 失敗:`, err);
    }
}

// 3. 自動同步更新 Package.appxmanifest (MSIX 清單) 版本號
const manifestPath = path.join(__dirname, '..', 'Package.appxmanifest');
if (fs.existsSync(manifestPath)) {
    try {
        let manifestContent = fs.readFileSync(manifestPath, 'utf8');
        // 使用正則表達式尋找 <Identity ... Version="x.y.z.w" /> 並替換
        manifestContent = manifestContent.replace(
            /(<Identity\s+[^>]*Version=")([^"]*)(")/,
            `$1${fullVersion}$3`
        );
        fs.writeFileSync(manifestPath, manifestContent, 'utf8');
        console.log(`[Sync] Package.appxmanifest 版本號已同步更新為: ${fullVersion}`);
    } catch (err) {
        console.error(`[Sync] 更新 Package.appxmanifest 失敗:`, err);
    }
}

// 4. 自動產生與更新 src/version.js 版本資訊檔
const versionJsPath = path.join(__dirname, '..', 'src', 'version.js');
try {
    const versionJsContent = `// Automatically generated by increment-build.js. Do not edit.
window.AppVersionInfo = {
  version: "${baseVersion}",
  buildVersion: "${fullVersion}",
  author: "${packageJson.author || 'mesmerli'}"
};
`;
    fs.writeFileSync(versionJsPath, versionJsContent, 'utf8');
    console.log(`[Sync] src/version.js 已同步更新為: ${baseVersion}`);
} catch (err) {
    console.error(`[Sync] 更新 src/version.js 失敗:`, err);
}



